code/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import CustomLoginForm


app_name = 'account'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html', authentication_form=CustomLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change.html'), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'), name='password_change_done'),

    path('register/', views.register, name='register'),

    path('dashboard/', views.dashboard, name='dashboard'),
    
    
]


# htmx_urlpatterns = [
#     path('check-if-username-exists/', views.check_if_username_exists, name='check_if_username_exists'),
# ]



# urlpatterns += htmx_urlpatterns

code/cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'



urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    # path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),

    ]

htmx_urlpatterns = [
    path('add_remove_from_cart/<int:product_id>', views.add_remove_from_cart, name='add_remove_from_cart'),
    path('refresh-cart-content', views.refresh_cart_content, name='refresh_cart_content'),

]


urlpatterns += htmx_urlpatterns

code/shop/urls.py
from django.urls import path
from . import views



app_name = 'shop'



urlpatterns = [
    path('', views.product_list, name='product_list'),

    path(
        '<slug:category_slug>/',
        views.product_list,
        name='product_list_by_category'
        ),
    
    path(
        '<int:id>/<slug:slug>/',
        views.product_detail,
        name='product_detail'
        ),
    
    path(
        'toggle-favorite/<int:product_id>', 
        views.toggle_favorite, 
        name='toggle_favorite'),

    ]


htmx_urlpatterns = [
    path('product-filter', views.product_filter, name='product_filter'),
]


urlpatterns += htmx_urlpatterns

code/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="cs">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Filatelie Štafl</title>

  <link rel="icon" href="{% static 'images/logo/e-logo.png' %}" />

  <!-- ========== fonts css ========== -->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
    rel="stylesheet" />

  <!-- ========== bootstrap css ========== -->
  <link rel="stylesheet" href="{% static 'css/vendors/bootstrap.css' %}" id="rtl-link" />

  <!-- ========== swiper css ========== -->
  <link rel="stylesheet" href="{% static 'css/vendors/swiper-bundle.css' %}" />

  <!-- ========== remix icon css ========== -->
  <link rel="stylesheet" href="{% static 'fonts/remix-icon/remixicon.css' %}" />

  <!-- ========== animation css ========== -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

  <!-- ========== style css ========== -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <!-- ========== htmx ========== -->
  <script src="https://unpkg.com/htmx.org@2.0.4"
    integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+"
    crossorigin="anonymous"></script>
</head>

<body class="montserrat-font">

  {% include './header.html' %}

  {% block content %}{% endblock %}

  {% include './footer.html' %}

</body>






<!-- ========== bootstrap js ========== -->
<script src="{% static 'js/vendors/bootstrap.min.js' %}"></script>
<script src="{% static 'js/vendors/popper.min.js' %}"></script>

<!-- ========== swiper js ========== -->
<script src="{% static 'js/vendors/swiper-bundle.min.js' %}"></script>

<!-- ========== custom swiper js ========== -->
<script src="{% static 'js/custom-slider.js' %}"></script>

<!-- ========== filter js ========== -->
<script src="{% static 'js/filter.js' %}"></script>

<!-- ========== Mood Button js ========== -->
<script src="{% static 'js/theme-setting.js' %}"></script>

<!-- ========== newsletter js ========== -->
<script src="{% static 'js/newsletter.js' %}"></script>

<!-- ========== Loader js ========== -->
<!-- <script src="{% static 'js/loader.js' %}"></script> -->

<!-- ========== script js ========== -->
<script src="{% static 'js/script.js' %}"></script>

code/templates/base/breadcrumb.html
<!-- ========== Start breadcrump Section ========== -->
<nav class="breadcrumb section-md-t-space section-md-b-space">
    <div class="custom-container">
        <!-- <img src="assets/images/breadcrumb-img.png" class="img-fluid breadcrumb-img" alt="breadcrumb-img" /> -->
        <div class="breadcrumb-box">
            <a class="breadcrumb-item" href="index.html">home</a>
            <span class="breadcrumb-item active" aria-current="page">Obchod</span>
        </div>
    </div>
</nav>
<!-- ========== End breadcrump Section ========== -->

code/templates/base/footer.html
{% load static %}

<!-- ========== Start Section ========== -->
<footer class="footer-section">
    <div class="custom-container">
        <div class="row section-sm-b-space g-0 g-sm-4">
            <div class="col-xl-4 col-lg-6 col-sm-6">
                <div class="footer-content">
                    <a href="#" class="logo main-logo">
                        <img src="{% static 'images/logo/logo-stafl.jpg' %}" alt="" />
                    </a>
                    <div class="footer-details">
                        <p>Adresa: <span>Palackého 80, Jablonec nad Nisou</span></p>
                        <a href="tel:(123) 456-7890">Telefon: <span>+420 123 456 789</span></a>
                        <a href="mailto:edgy@contact.no">Email: <span>info@stafl.cz</span></a>
                    </div>
                    <div class="footer-social">
                        <a href="#"><i class="ri-facebook-fill"></i></a>
                        <!-- <a href="#"><i class="ri-google-fill"></i></a> -->
                        <!-- <a href="#"><i class="ri-twitter-x-fill"></i></a> -->
                        <a href="#"><i class="ri-instagram-line"></i></a>
                    </div>
                </div>
            </div>
            <div class="menu-box folder-menu col-xl-2 col-lg-3 col-sm-6">
                <h5>Společnost</h5>
                <ul class="footer-menu">
                    <li><a href="#" class="footer-link">O nás</a></li>
                    <li><a href="#" class="footer-link">Kontakt</a></li>
                    <li><a href="#" class="footer-link">FAQs</a></li>

                    <li><a href="#" class="footer-link">Hledat</a></li>
                </ul>
            </div>
            <div class="menu-box folder-menu col-xl-2 col-lg-3 col-sm-6">
                <h5>Odkazy</h5>
                <ul class="footer-menu">
                    <li><a href="#" class="footer-link">Domů</a></li>
                    <li><a href="#" class="footer-link">Obchod</a></li>
                    <li><a href="#" class="footer-link">Přihlásit</a></li>
                    <li><a href="#" class="footer-link">Registrovat</a></li>
                </ul>
            </div>
            <div class="menu-box col-xl-4 col-sm-6">
                <h5>Newsletter</h5>
                <div class="footer-menu">
                    <p class="news-letter-head">
                        Přihlaste se k odběru našeho newsletteru ještě dnes!
                    </p>
                    <form class="news-latter-input">
                        <input type="email" placeholder="Email" />
                        <button type="submit" class="btn solid-btn box-sm-radius">
                            <div class="button-text">
                                <span>Přihlásit</span>
                            </div>
                        </button>
                    </form>
                </div>
            </div>
        </div>
        <div class="footer-sub-menu">
            <h6>
                Copyright <i class="ri-copyright-line"></i> 2025 Zdeněk Štafl
            </h6>
            <a href="#" class="footer-img">
                <img src="{% static 'images/payment/1.png' %}" class="img-fluid" alt="" />
            </a>
        </div>
    </div>
</footer>
<!-- ========== End Section ========== -->

code/templates/base/header.html
{% load static %}

<!-- ========== Start header Section ========== -->
<header class="header-wrapper">
    <div class="main-header">
        <div class="custom-container">
            <div class="main-sub-head">
                <div class="left-header">
                    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
                        data-bs-target="#primaryMenu" aria-controls="primaryMenu">
                        <span><i class="ri-align-left text-dark"></i></span>
                    </button>
                    <a href="{% url 'home' %}" class="main-logo">
                        <img src="{% static 'images/logo/logo-stafl.png' %}" class="light-logo" alt="" />
                        <img src="{% static 'images/logo/logo-stafl.png' %}" class="dark-logo" alt="" />
                    </a>
                </div>

                <!-- Navigation Start -->
                <nav class="navigation">
                    <div class="nav-section">
                        <div class="header-section">
                            <div class="navbar navbar-expand-xl navbar-light navbar-sticky p-0">
                                <div class="offcanvas sidebar-menu offcanvas-collapse order-lg-2" id="primaryMenu">
                                    <div class="offcanvas-header sidebar-offcanvas">
                                        <h5 class="mt-1 mb-0">Menu</h5>
                                        <button class="close-offcanvas lead" type="button" data-bs-dismiss="offcanvas"
                                            aria-label="Close">
                                            <i class="ri-close-fill"></i>
                                        </button>
                                    </div>
                                    <div class="offcanvas-body">
                                        <!-- Menu-->
                                        <ul class="navbar-nav">
                                            <!-- Home -->
                                            <li class="nav-item dropdown dropdown-mega">
                                                <a class="nav-link dropdown-toggle text-dark" href="#"
                                                    data-bs-toggle="dropdown">Domů</a>
                                                <!-- <div class="dropdown-menu home-menu">
                                                    <div class="row g-lg-4 g-3">
                                                        <div class="col-xl-3 col-6 mega-box">
                                                            <a class="home-box" href="">
                                                                <img class="img-fluid"
                                                                    src="{% static 'images/demo-image/demo-1.png' %}"
                                                                    alt="home1" />
                                                                <span>Demo - 1</span>
                                                            </a>
                                                        </div>


                                     
                                                    </div>
                                                </div> -->
                                            </li>

                                            <!-- Shop -->
                                            <li class="nav-item dropdown">
                                                <a class="nav-link dropdown-toggle text-dark"
                                                    data-bs-toggle="dropdown">Obchod</a>
                                                <div class="dropdown-menu custom-drop-menu">
                                                    <div class="dropdown-column">
                                                        <a class="dropdown-item"
                                                            href="{% url 'shop:product_list' %}">Vše</a>

                                                        <!-- Add other shop links -->
                                                    </div>
                                                </div>
                                            </li>

                                            <!-- Blog -->
                                            <li class="nav-item dropdown">
                                                <a class="nav-link dropdown-toggle text-dark"
                                                    data-bs-toggle="dropdown">Blog</a>
                                                <div class="dropdown-menu custom-drop-menu">
                                                    <div class="dropdown-column">
                                                        <a class="dropdown-item"
                                                            href="{% url 'shop:product_list' %}">Vše</a>


                                                    </div>
                                                </div>
                                            </li>

                                            <!-- About -->
                                            <li class="nav-item dropdown">
                                                <a class="nav-link dropdown-toggle text-dark"
                                                    data-bs-toggle="dropdown">O nás</a>
                                                <div class="dropdown-menu custom-drop-menu">
                                                    <div class="dropdown-column">
                                                        <a class="dropdown-item"
                                                            href="{% url 'shop:product_list' %}">Vše</a>

                                                    </div>
                                                </div>
                                            </li>

                                            <!-- Account -->
                                            <li class="nav-item dropdown">
                                                <a class="nav-link dropdown-toggle text-dark"
                                                    data-bs-toggle="dropdown">Kontakt</a>
                                                <div class="dropdown-menu custom-drop-menu">
                                                    <div class="dropdown-column">
                                                        <a class="dropdown-item"
                                                            href="{% url 'shop:product_list' %}">Vše</a>

                                                    </div>
                                                </div>
                                            </li>


                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
                <!-- Navigation End -->

                <ul class="user-section main-user-menu">
                    <li class="home-icon">
                        <a href="" class="active text-dark"><i class="ri-home-4-line"></i></a>
                    </li>
                    <li class="search-menu">
                        <a href="#!" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight"
                            aria-controls="offcanvasRight"><i class="ri-search-line text-dark"></i>
                        </a>
                    </li>
                    <li>
                        <a href=""><i class="ri-heart-line text-dark"></i><span id="cart-wishlist-count"
                                class="cart-box text-white"> {{ request.user.profile.wishlist.all|length }}
                            </span></a>
                    </li>
                    <li class="menu-link">

                        {% include 'cart/nav_component.html' %}

                    </li>
                    <li class="menu-link">
                        <a href="{% url 'account:dashboard' %}" class="user-box">
                            <i class="ri-user-3-line text-dark"></i>
                            <div class="user-detail">
                                {% if request.user.is_authenticated %}
                                <h6 class="text-dark">Přihlášen:</h6>
                                <h5 class="text-dark">{{ request.user }}</h5>
                                {% else %}
                                <h6 class="text-dark">Přihlásit se</h6>
                                {% endif %}
                            </div>
                        </a>
                        {% if request.user.is_authenticated %}
                        <ul class="sub-menu login-menu">
                            <li>
                                <a href="{% url 'account:dashboard' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="sub-link mt-0 bg-transparent border-0">Zobrazit profil</button>
                                </a>
                            </li>
                            <!-- <li>
                  <a href="" class="sub-link mt-0">Register</a>
                </li>
                <li>
                  <a href="" class="sub-link mt-0">Forgot password</a>
                </li> -->
                        </ul>
                        {% endif %}
                    </li>
                    <!-- ========== Start Theme Button ========== -->
                    <li>
                        <button class="mode-change-button bg-white border-2 rounded-circle">
                            <i id="themeIcon" class="ri-moon-line text-black fs-4"></i>
                        </button>
                    </li>
                    <!-- ========== End Theme Button ========== -->
                </ul>
            </div>
        </div>
    </div>
</header>
<!-- ========== End header Section ========== -->