code/cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'



urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    # path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),

    ]

htmx_urlpatterns = [
    path('add_remove_from_cart/<int:product_id>', views.add_remove_from_cart, name='add_remove_from_cart'),
    path('refresh-cart-content', views.refresh_cart_content, name='refresh_cart_content'),

]


urlpatterns += htmx_urlpatterns

code/shop/urls.py
from django.urls import path
from . import views



app_name = 'shop'



urlpatterns = [
    path('', views.product_list, name='product_list'),

    path(
        '<slug:category_slug>/',
        views.product_list,
        name='product_list_by_category'
        ),
    
    path(
        '<int:id>/<slug:slug>/',
        views.product_detail,
        name='product_detail'
        ),
    
    path(
        'toggle-favorite/<int:product_id>', 
        views.toggle_favorite, 
        name='toggle_favorite'),

    ]


htmx_urlpatterns = [
    path('product-filter', views.product_filter, name='product_filter'),
]


urlpatterns += htmx_urlpatterns

code/templates/shop/product/partials/btn_cart.html
<a href="" id="cart-button-{{ product.id }}" hx-get="{% url 'cart:add_remove_from_cart' product.id %}"
    hx-target="#cart-button-{{ product.id }}" hx-swap="outerHTML"
    class="btn {% if is_in_cart %} outline-btn {% else %} outline-btn {% endif %} ">
    <i class="ri-shopping-cart-2-line"></i>

    {% if is_in_cart %}
    Odebrat z košíku
    {% else %}
    Přidat do košíku
    {% endif %}
</a>

<div id="cart-products-count" hx-swap-oob="innerHTML" style="display: none;">
    {{ cart|length}}
</div>

code/templates/shop/product/partials/btn_wishlist.html
<a href="" id="favorite-button-{{ product.id }}" hx-get="{% url 'shop:toggle_favorite' product.id %}"
    hx-target="#favorite-button-{{ product.id }}" hx-swap="outerHTML"
    class="like-btn animate {% if is_favorite %}active{% else %}inactive{% endif %} p-0">
    <i class="ri-heart-3-fill fill-icon"></i>
    <i class="ri-heart-3-line outline-icon"></i>
    {% if is_favorite %}
    Remove From Wishlist
    {% else %}
    Add To Wishlist
    {% endif %}
</a>

<div id="cart-wishlist-count" hx-swap-oob="innerHTML" style="display: none;">
    {{ request.user.profile.wishlist.all|length}}
</div>

code/templates/shop/product/partials/cards.html
{% for product in products %}
<div class="col-grid-box show">
    <div class="product-box w-75">
        <div class="product-img-box">
            <div class="label-box">
                <div class="product-option">
                    {% if product in favorite_products %}
                    <a href="" class="like-btn wishlist-btn p-0 animate active">
                        <i class="ri-heart-3-fill fill-icon fill-two"></i>
                        <i class="ri-heart-3-line outline-icon like-two"></i>
                    </a>
                    {% else %}
                    <a href="" class="like-btn wishlist-btn p-0 animate inactive">
                        <i class="ri-heart-3-fill fill-icon fill-two"></i>
                        <i class="ri-heart-3-line outline-icon like-two"></i>
                    </a>
                    {% endif %}
                    <!-- <a href="#!" class="sub-link mt-0" data-bs-toggle="modal" data-bs-target="#view"><i
                            class="ri-eye-line"></i></a>
                    <a href="#!"><i class="ri-loop-right-fill"></i></a> -->
                </div>
            </div>
            <div class="front">
                <a href="{% url 'shop:product_detail' product.id product.slug %}">
                    <img src="{{ product.image.url }}" class="bg-img w-100" alt="" />
                </a>
            </div>
            <div class="back">
                <a href="{% url 'shop:product_detail' product.id product.slug %}">
                    <img src="" class="bg-img w-100" alt="" />
                </a>
            </div>
            <div class="product-btn">
                <a href="#" class="btn solid-btn addtocart-btn">
                    <div class="button-text">
                        <span>Mám zájem</span>
                    </div>
                </a>
            </div>
        </div>
        <div class="product-detail text-center">
            <div class="product-name-box">
                <a href="{% url 'shop:product_detail' product.id product.slug %}"
                    class="product-name">{{product.name}}</a>

            </div>
            <p class="list-detail">
                {{ product.description }}
            </p>
            <h6 class="product-price">{{ product.price}} Kč</h6>
        </div>
    </div>
</div>
{% endfor %}