code/cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'



urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    # path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),

    ]

htmx_urlpatterns = [
    path('add_remove_from_cart/<int:product_id>', views.add_remove_from_cart, name='add_remove_from_cart'),
    path('refresh-cart-content', views.refresh_cart_content, name='refresh_cart_content'),

]


urlpatterns += htmx_urlpatterns

code/shop/urls.py
from django.urls import path
from . import views



app_name = 'shop'



urlpatterns = [
    path('', views.product_list, name='product_list'),

    path(
        '<slug:category_slug>/',
        views.product_list,
        name='product_list_by_category'
        ),
    
    path(
        '<int:id>/<slug:slug>/',
        views.product_detail,
        name='product_detail'
        ),
    
    path(
        'toggle-favorite/<int:product_id>', 
        views.toggle_favorite, 
        name='toggle_favorite'),

    ]


htmx_urlpatterns = [
    path('product-filter', views.product_filter, name='product_filter'),
]


urlpatterns += htmx_urlpatterns

code/cart/models.py
from django.db import models

# Create your models here.

code/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.http import HttpResponse


from .cart import Cart
from shop.models import Product



def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})



# @require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')






###############################################################
# HTMX VIEWS:
###############################################################

def add_remove_from_cart(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    
    if product in cart:
        cart.remove(product)
        is_in_cart = False
    else:
        cart.add(product=product)
        is_in_cart = True

    # Return the updated button HTML
    return HttpResponse(render(request, 'shop/product/partials/btn_cart.html', {
        'product': product,
        'is_in_cart': is_in_cart,
    }))



def refresh_cart_content(request):
    cart = Cart(request)
    return render(request, 'cart/partials/items.html', {'cart': cart})

code/templates/cart/partials/items.html
<div id="cart-component-products">
    <div class="product-contain">
        {% for item in cart %}
        {% with product=item.product %}
        <div class="cart-menu">
            <a href="" class="cart-img-box">
                <img src="{{product.image.url }}" class="cart-img img-fluid" alt="product" />
            </a>
            <div class="drop-cart">
                <div>
                    <a href="{% url 'shop:product_detail' product.id product.slug %}">
                        <h6>{{ product.name }}</h6>
                    </a>
                    <p>
                        {{ product.price }} Kč
                    </p>
                </div>
                <!-- <a href="" class="close-btn">
            <i class="ri-delete-bin-5-line"></i>
        </a> -->
            </div>
        </div>
        {% endwith %}
        {% endfor %}

    </div>

    <div class="cart-price">
        <h6>Celkem:</h6>
        <h5>{{ cart.get_total_price }} Kč</h5>
    </div>
</div>

code/templates/cart/partials/products.html
<tbody id="cart-products">

    {% for item in cart %}
    {% with product=item.product %}


    <tr>
        <td>
            <div class="product-cart-box">
                <a href="#!" class="product-cart-img">
                    <img src="{{ product.image.url }}" class="img-fluid" alt="" />
                </a>
                <div class="product-cart-detail">
                    <h5 class="product-cart-name">
                        {{ product.name }}
                    </h5>
                    <p>
                        {{ product.description }}
                    </p>
                </div>
            </div>
        </td>
        <td class="cart-attribute">
            <p>{{ product.category }}</p>

        </td>
        <td>
            <div class="counter cart-counter">
                <span class="down" onClick="decreaseCount(event, this)">
                    <i class="ri-subtract-line"></i></span>
                <input type="text" value="{{ item.quantity }}" />
                <span class="up" onClick="increaseCount(event, this)">
                    <i class="ri-add-line"></i></span>
            </div>
        </td>
        <td class="product-cart-price">{{ product.price }}</td>
        <td>
            <div class="deleteButton">
                <a href="{% url 'cart:cart_remove' product.id %}"><i class="ri-delete-bin-line"></i></a>
            </div>
        </td>
    </tr>

    {% endwith %}

    {% endfor %}

</tbody>